baseURL = 'https://geauxweisbeck4.dev/'
languageCode = 'en-us'
title = 'GeauxWeisbeck4.dev'
theme = 'digitalgarden'

googleAnalytics = "UA-PROPERTY_ID"

[Params]
  description = "Andrew Weisbeck's digital garden for sharing knowledge about software development, philosophy, and everything in between."
  images = ['/digital_office.png']
  enableSearch = true

[Params.newsletter]
  title = "WeisMind Newsletter"
  description = "A newsletter to help you sharpen your mind, live without fear, and discover true freedom."
  provider = "substack"
  path = "https://substack.com/@weismind"

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Content'
  params.header = true
  weight = 2
[[menu.main]]
  name = 'Articles'
  url = '/articles'
  weight = 3
[[menu.main]]
  name = 'Note Catalog'
  url = '/note-catalog'
  weight = 4
[[menu.main]]
  name = 'Portfolio'
  url = '/portfolio'
  weight = 5
[[menu.main]]
  name = 'Stack'
  url = '/stack'
  weight = 6
[[menu.main]]
  name = 'Support'
  url = '/support'
  weight = 7
[[menu.main]]
  name = 'Links'
  params.header = true
  weight = 8
[[menu.main]]
  name = 'Tar Heel Dev Studio'
  url = 'https://tarheeldevstudio.com'
  weight = 9
[[menu.main]]
  name = 'My Portfolio/Resume Site'
  url = 'https://andrewweisbeck.com'
  weight = 10
[[menu.main]]
  name = 'GeauxCode.dev'
  url = 'https://geauxcode.dev'
  weight = 11
[[menu.main]]
  name = 'Medium Blog'
  url = 'https://geauxweisbeck4.medium.com/'
  weight = 12
[[menu.main]]
  name = 'Dev.to Blog'
  url = 'https://dev.to/geauxweisbeck4'
  weight = 13
[[menu.main]]
  name = 'Ko-Fi'
  url = 'https://ko-fi.com/geauxweisbeck4'
  weight = 14
[[menu.main]]
  name = 'Patreon'
  url = 'https://patreon.com/geauxweisbeck4'
  weight = 15

[[menu.social]]
  name = 'GithHub'
  url = 'https://github.com/geauxweisbeck4'
  weight = 1
[[menu.social]]
  name = 'GitLab'
  url = 'https://gitlab.com/geauxweisbeck4'
  weight = 2
[[menu.social]]
  name = 'LinkedIn'
  url = 'https://linkedin.com/in/geauxweisbeck4'
  weight = 3
[[menu.social]]
  name = 'Mastodon'
  url = 'https://fosstodon.org/geauxweisbeck4'
  weight = 4
[[menu.social]]
  name = 'Codepen'
  url = 'https://codepen.io/geauxweisbeck4'
  weight = 5
[[menu.social]]
  name = 'Dribbble'
  url = 'https://dribbble.com/geauxweisbeck4'
  weight = 6
[[menu.social]]
  name = 'Instagram'
  url = 'https://instagram.com/geauxweisbeck4'
  weight = 7
[[menu.social]]
  name = 'Twitter'
  url = 'https://twitter.com/geauxweisbeck4'
  weight = 8
[[menu.social]]
  namee = 'RSS'
  url = '/articles/index.html'
  weight = 9

# Syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true